import 'package:get/get.dart';

/// 国际化
class HuuuaTranslate extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'zh_CN': {
      'home': '发现',
      'mine': '我的',
      'set': '设置',
      'bible': '圣经',
      'language': '语言',
      'country': '国家',
      'ot': '旧约',
      'nt': '新约',
      'mybible': '我的圣经',
      'Brightness': '亮度',
      'TextSize': '文字大小',
      'LineHeight': '行高',
      'default_': '默认',
      'input_keyword': '输入关键字',
      'search': '搜索',
      'nothing_tip': '很抱歉，没有内容！',
      'font_style': '字体',
      'share': '分享',
      'movie': '电影',
      'search_placetext': '搜索...',
      'bible_version': '圣经版本',
      'view_all': '查看全部',
      'Loading_video': '加载视频中...',
      'netlinkfailed': '网络连接失败,请检查网络设置',
      'retry': '重试',
      'privacypolicy': '隐私政策',
      'termsofservice': '用户协议', //服务条款
      'clearcache': '清除缓存',
      'checkofupdate': '检查更新',
      'currentversion': '当前版本',
      'rating': '评分',
      'feedback': '反馈',
      'feedbackcontent': '请前往商店评论区留言反馈!',
      'CANCEL': '退出',
      'GO': '前往',
      'Share': '分享',
      'loading': '初始化...',
      'sharecontent': '圣经App分享给您！',
      'login_policy_tip': '登录即代表同意我们的用户协议和隐私政策',
      'privacy_policy': '隐私政策',
      'terms_of_services': '服务条款',
      "Please log in before commenting.": "请登录后再评论",
      "login": "登录",
      "Tip": "提示",
      "Reply": "回复",
      "Show @count more replie": "-----展开 @count 条回复 ▼",
      "Write a comment…": "发表评论…",
      "All Comments": "全部评论",
      "Replies to this comment": "该评论的全部回复",
      "Not logged in": "未登录",
    },
    'en_US': {
      'home': 'Discover',
      'mine': 'Mine',
      'set': 'Set',
      'bible': 'Bible',
      'language': 'Language',
      'country': 'Country',
      'ot': 'Old Testament',
      'nt': 'New Testament',
      'mybible': 'My Bible',
      'Brightness': 'Brightness',
      'TextSize': 'Text Size',
      'LineHeight': 'Line Height',
      'default_': 'Default',
      'input_keyword': 'Input Keyword',
      'search': 'Search',
      'nothing_tip': 'Sorry, there is no content!',
      'font_style': 'Font Style',
      'share': 'Share',
      'movie': 'Movie',
      'search_placetext': 'Search...',
      'bible_version': 'Bible Version',
      'view_all': 'See All',
      'Loading_video': 'Loading video...',
      'netlinkfailed':
          'Network connection failed！\n Please check your network setings.',
      'retry': 'Retry',
      'privacypolicy': 'Privacy Policy',
      'termsofservice': 'Terms of Service', //服务条款
      'clearcache': 'Clear Cache',
      'checkofupdate': 'Check',
      'currentversion': 'Current Version',
      'rating': 'Rating',
      'feedback': 'FeedBack',
      'feedbackcontent':
          'Please leave a message and feedback in the store comments section!',
      'CANCEL': 'CANCEL',
      'GO': 'GO',
      'Share': 'Share',
      'loading': 'Loading...',
      'sharecontent': 'The bible app to share with you！',
      'login_policy_tip': 'By createing an account,I accept',
      'privacy_policy': 'Privacy Policy',
      'terms_of_services': 'Terms of Services',
      "Please log in before commenting.": "Please log in before commenting.",
      "login": "login",
      "Tip": "Tip",
      "Reply": "Reply",
      "Show @count more replie": "-----Show @count more replies ▼",
      "Write a comment…": "Write a comment…",
      "All Comments": "All Comments",
      "Replies to this comment": "Replies to this comment",
      "Not logged in": "Not logged in",
      "Just now": "Just now",
      "@time minutes ago": "@time minutes ago",
      "@time hours ago": "@time hours ago",
      "@time days ago": "@time days ago",
    },
  };
}
